import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta charSet="UTF-8" />
      <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>My Portfolio</title>
      <link rel="stylesheet" href="/style.css" />
      <link rel="stylesheet" href="/mediaqueries.css" />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
